.TH SDHCP-VERSION 1
.SH NAME
sdhcp \- a simple dhcp client
.SH SYNOPSIS
.B sdhcp
.RB [ \-d ]
.RB [ \-i ]
.RB "[ \-e"
.IR "program"
.RB "]"
.RB "[ "
.IR interface
.RB "]"
.RB "["
.IR "client\-id"
.RB "]"
.SH DESCRIPTION
sdhcp is a simple, tiny dhcp client. It runs until it enters the "Bound"
state, then forks to the background and runs as a daemon to keep
the lease alive.
.SH OPTIONS
.TP
.B \-d
don't change DNS in /etc/resolv.conf.
.TP
.B \-i
don't change interface information such as an IP address.
.TP
.B "\-e program"
run program. Variables will be set, see VARIABLES.
.SH VARIABLES
.LP
The following variables are set:
.LP
$SERVER    DHCP IP.
.LP
$DNS       DNS IP.
.LP
$ROUTER    router IP.
.LP
$MASK      network mask.
.LP
$CLIENT    your client IP.
.SH BUGS
I'm sure there's plenty. It only currently supports a small subset of
DHCP options, and has been untested on larger networks. It ignores most of
the DHCP options it understands. Send bug reports to me!
.SH AUTHOR
see LICENSE file
